# Generated by Django 5.0 on 2024-04-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviews_created_alter_reviews_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
