# Generated by Django 5.0 on 2024-04-28 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_reviews_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 19, 39, 12, 744170), null=True),
        ),
    ]
