# Generated by Django 5.0 on 2024-04-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_reviews_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
