# Generated by Django 5.0.6 on 2024-08-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages='Username is required', help_text='username must be unique', max_length=50, unique=True),
        ),
    ]
