# Generated by Django 5.0 on 2024-04-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages='Email is required', help_text='Must be an email', max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
