# Generated by Django 5.0 on 2024-04-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages='Email is required', max_length=50, unique=True, verbose_name='Email'),
        ),
    ]
