# Generated by Django 5.0 on 2024-04-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages='Username is required', help_text='username must be unique', max_length=50),
        ),
    ]
