# Generated by Django 5.0.6 on 2024-06-03 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image_url', models.FileField(upload_to='products/')),
                ('descount', models.FloatField()),
                ('paid', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(null=True)),
                ('total_price', models.IntegerField(null=True)),
                ('product_id', models.CharField(max_length=200, null=True)),
                ('product', models.ManyToManyField(to='Products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'Orders',
                'ordering': ['-name'],
            },
        ),
    ]
