# Generated by Django 5.0 on 2024-01-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_remove_order_product_alter_order_user_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stock',
        ),
    ]
