# Generated by Django 5.0 on 2024-01-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_order_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-name']},
        ),
    ]
