# Generated by Django 5.0 on 2024-01-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-name'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
    ]
