# Generated by Django 5.0 on 2024-04-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_product_image_url_productimage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimage',
            table='images',
        ),
    ]
