# Generated by Django 5.0 on 2024-04-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_productimage_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
    ]
