# Generated by Django 5.0 on 2024-01-25 22:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='django/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.FileField(blank=True, upload_to='products/'),
        ),
    ]
