# Generated by Django 5.0 on 2024-01-25 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_remove_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-stock', '-price']},
        ),
    ]
