# Generated by Django 5.0 on 2024-05-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_mark_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
